### PR TITLE
Clarify install instructions

### PR DESCRIPTION
**Pull request by asivitz**
Also standardize location of socket so it doesn't need to be user-configured

### CODE REVIEW

**Comment by carlosdcastillo** [comment]
@asivitz That is awesome. Thanks!

**Comment by jordwalke** [comment]
Awesome! Curious, where do you install the dependencies (with `npm install`)? Which directory?

**Comment by asivitz** [comment]
Oh, I made a mistake. Try this instead:
$ cd .atom/packages/vim-mode
$ apm install
That should read the dependencies from the package.json and install them in the proper place. I'll add another PR for this change.

I'm new to node and Atom development though, so there might be a better command.

**Comment by carlosdcastillo** [comment]
I've pulled the fixed instructions. @jordwalke Let us know if the fixed instructions allowed you to install the software.

**Pull request merged**
